LANG,0

FILE,242
0 "RECOMP - DETECTED"
0 "PRESENTED IN DOLBY SURROUND. DOLBY AND THE       SYMBOL ARE TRADEMARKS OF DOLBY LABORATORIES."
0 "USES MILES SOUND SYSTEM. COPYRIGHT 1991-1999 RAD GAME TOOLS INC."
0 "MPEG LAYER-3 PLAYBACK SUPPLIED WITH THE MILES SOUND SYSTEM FROM RAD GAME TOOLS\,INC. MPEG LAYER-3 AUDIO COMPRESSION TECHNOLOGY LICENSED BY FRAUNHOFER IIS AND THOMSON MULTIMEDIA.       n       n       n       n       n       n       n       n       n       n       n       n           n           PATCHES BY DINOSAUR PLANET COMMUNITY."
0 "COPYRIGHT RARE 2000."
