[manifest]
id = "dinomod_enhanced"
display_name = "Dinomod Enhanced"
description =  """
A work-in-progress mod porting over Dinomod Enhanced's ROM fixes to recomp.
"""
short_description = "WIP port of Dinomod Enhanced patches"

version = "0.8.0"
authors = [ "Banjeoin", "jeebs2kx", "LaminGaming", "MusicalProgrammer", "Shinx121", "nuggs" ]

game_id = "dino-planet"
minimum_recomp_version = "0.3.0"

dependencies = [
    
]

native_libraries = [
# Example native library:
#    { name = "my_native_library", funcs = ["my_native_library_function"] }
]

[inputs]
elf_path = "build/mod.elf"
mod_filename = "dinomod_enhanced"
func_reference_syms_file = "../lib/dino-recomp-decomp-bridge/dino.syms.toml"
data_reference_syms_files = [
    "../lib/dino-recomp-decomp-bridge/dino.datasyms.toml", 
    "../lib/dino-recomp-decomp-bridge/dino.datasyms_manual.toml", 
    "../dino.datasyms_extra.toml"
]
additional_files = [
    "thumb.png"
]

[[manifest.config_options]]
id = "gametext_flavor"
name = "Text: Flavor"
description = '''
Which version of Dinomod Enhanced's subtitle/text patches to use.

- Vanilla: Preserves vanilla subtitles and text while including fixes and new translations.
- Cosmetic: In addition to Vanilla, adds coloured subtitles along with additional subtitles for various things like sound effects. 
'''
type = "Enum"
options = [ "Vanilla", "Cosmetic" ]
default = "Vanilla"

[[manifest.config_options]]
id = "lamingaming_extra_description_text"
name = "Text: Add Extra Descriptions"
description = '''
Adds custom description text for inventory items, objects, and characters that had yet to have text created for them. Many of these strings are sourced from DP leftovers in Star Fox Adventures' Kiosk build, or from appropriate counterparts in SFA itself.

[Originally created by LaminGaming]
'''
type = "Enum"
options = [ "Off", "On"]
default = "On"

[[manifest.config_options]]
id = "upcoming_subtitle_trans"
name = "Text: Upcoming Subtitle Transparency"
description = '''
In the vanilla game, the upcoming subtitle text is shown behind the current subtitle text with low transparency. This option lets you turn upcoming text invisible instead, for improved clarity. This is left as an option since the upcoming text being visible early may have been an intentional style choice by Rare. 
'''
type = "Enum"
options = [ "Vanilla", "Invisible" ]
default = "Invisible"

[[manifest.config_options]]
id = "pickup_jingle"
name = "Audio: Item Pickup Jingle"
description = '''
Which version of the item pickup jingle to play.

- Old (variant A)
  A slower arrangement of the original pickup jingle.

- Old (variant B)
  The original pickup jingle as heard in the One Hour Footage.

- New 
  The Star Fox themed jingle played in the December 2000 Prototype.
'''
type = "Enum"
options = [ "Old (variant A)", "Old (variant B)", "New" ]
default = "Old (variant B)"

[[manifest.config_options]]
id = "button_tap_modes"
name = "Accessibility: Button Tapping"
description = '''
There are two prominent sections of gameplay in Dinosaur Planet that involve rapid button tapping: the Test of Strength shrine, and the LightFoot Strength Trial.

This config setting provides a number of options for adjusting these sections:

- Off
  The default gameplay (but with framerate dependency bugs fixed*).

- On (Reduced)
  The sections can be completed with less frequent tapping.

- On (Hold)
  The player character will push while holding A, instead of tapping.

- On (Auto)
  The player character will push automatically.

*In the unmodified game, a limitation in the handling of buffered button presses creates a 25% chance for a single button press to accidentally be treated as several consecutive button presses when playing at low framerates. While this bug doesn't affect most gameplay, it does cause the LightFoot Strength Trial in particular to become roughly 50% more difficult when playing at smooth framerates, like in emulators or Recomp! Dinomod Enhanced fixes this framerate dependency.
'''
type = "Enum"
options = [ "Off", "On (Reduced)", "On (Hold)", "On (Auto)" ]
default = "Off"

[[manifest.config_options]]
id = "cmdmenu_new_controls"
name = "Inventory: New Controls"
description = '''
In the unpatched prototype you can only scroll down through an inventory page, which can make it easy to accidentally overshoot the desired item. 

This option revamps the controls for the C-button inventory, adding a way to scroll up as well as down!

As before, when the inventory is closed: 
- C-left opens Spells
- C-down opens Sidekick Commands
- C-right opens Items

What's different is, once the inventory is open:
- C-down moves down the page
- C-up moves up the page
- C-left switches to the previous page
- C-right switches to the next page 

(Switching to the next page works like:
Items>Sidekick, Sidekick>Spells, Spells>Items, etc.)

The new controls also let you hold C-up or C-down to scroll continuously through the inventory, without having to tap repeatedly.

The separate "Inventory: D-Pad Controls" config can be used in conjunction with the new controls!
'''
type = "Enum"
options = [ "Off", "On" ]
default = "Off"

[[manifest.config_options]]
id = "cmdmenu_d_controls"
name = "Inventory: D-Pad Controls"
description = '''
This lets you navigate the inventory using the D-pad! Here are the modes:

- Off
 Only the C-buttons navigate the inventory.

- On (D-Pad & C-Buttons)
 Both the D-pad and C-buttons can be used to navigate.

- On (D-Pad Only)
 Only the D-pad navigates, freeing up the C-buttons.

NOTE:
This D-pad config can be used with or without "Inventory: New Controls".
'''
type = "Enum"
options = [ "Off", "On (D-Pad & C-Buttons)", "On (D-Pad Only)" ]
default = "Off"

[[manifest.config_options]]
id = "cmdmenu_info_popup_fix"
name = "Item Pop-Up: Visual Fix"
description = '''
The game's UI has a feature where it can display an info pop-up in the bottom-left of screen upon collecting an item.

In the unpatched December 2000 Prototype the pop-up's visuals are slightly broken-looking, since it was designed around an older horizontally-scrolling version of the inventory menu seen in early footage.

This mod option fixes up its visuals so that it matches the later inventory design. It also prevents a clash between the minimap and the pop-up: ensuring one fades out before showing the other. The pop-up also stays on-screen if another of the displayed item is collected before the pop-up disappears.
'''
type = "Enum"
options = [ "Off", "On" ]
default = "On"

[[manifest.config_options]]
id = "cmdmenu_info_popup_expand"
name = "Item Pop-Up: More Uses"
description = '''
The game's UI has a feature where it can display an info pop-up in the bottom-left of screen upon collecting an item.

In the unpatched December 2000 Prototype this pop-up only appears when collecting Kyte's Grubs. This mod option expands the pool of items to include the following items:

- Energy Eggs
- Alpine Roots
- Blue Mushrooms
- White Mushrooms
- Purple Mushroom Spores
- Shiny Nuggets*
- DarkIce Mines Bridge Cogs*
- Fire Crystal

 (This list can be expanded over time, as more of the game is decompiled)

 * The item collection cutscene is usually shown every time these particular items are collected. Using the "On+" setting, the item's collection cutscene will be shown the first time it's collected, and then the pop-up will appear instead on subsequent collections.
'''
type = "Enum"
options = [ "Off", "On", "On+" ]
default = "On"

[[manifest.config_options]]
id = "cmdmenu_icons_gold_silver_keys"
name = "Inventory: Gold/Silver Key Icons"
description = '''
In the unmodified December 2000 Prototype, all of DarkIce Mines' keys use the same image for their inventory icon.

Star Fox Adventures' Kiosk build (2002) contains many leftover assets from earlier in development, for example a folder ("swapcircle") containing Dinosaur Planet inventory icons from around January 2001. Included among these is a unique N64-era texture for what looks like the Gold Key, which isn't found in December 2000's files!

Another folder from slightly later in development ("Copy of swaphol") includes what looks like the Silver Key. This one doesn't have the inventory background embedded and has a 64x48px resolution (up from 32x24px on N64).

This config option lets you use those icons for the Gold and Silver Keys! The Gold image is unmodified, and the Silver image has just been scaled down and composited with the background used by the N64 icons.
'''
type = "Enum"
options = [ "Off", "On" ]
default = "On"

[[manifest.config_options]]
id = "cmdmenu_icons_firefly"
name = "Inventory: Firefly Icon"
description = '''
Star Fox Adventures' Kiosk build (2002) contains many leftover assets from earlier in development, for example a folder ("swapcircle") containing Dinosaur Planet inventory icons from around January 2001.

A revised design for the Firefly Lantern's icon can be found among these files! It has the inventory background embedded, and has a 64x48px resolution (up from the N64 icons' usual 32x24px).

This config option lets you use the redesigned icon, or you can switch it off to continue using the icon from December 2000! The image has been scaled down to suit the resolution expected by the N64 icons.
'''
type = "Enum"
options = [ "Off", "On" ]
default = "On"

[[manifest.config_options]]
id = "cmdmenu_icons_energy_eggs"
name = "Inventory: Energy Egg Icons"
description = '''
After storing an Energy Egg in the player's Food Bag, you'll notice that it has a mismatched icon in the December 2000 Prototype: instead of an egg it shows a drumstick of meat.

This is an older design for the health refill collectables that can be seen in the One Hour Footage. Rare had redesigned the food and updated its 3D model by December 2000, but they had yet to create a new inventory icon and description for it.

If you enable this config option, the game will show a custom icon for the Energy Egg and its spoiled variant!

The icons were drawn/painted-over by Banjeoin, based off Nick Southam's unused PointBack egg minigame icons from the Kiosk's leftover files.
'''
type = "Enum"
options = [ "Off", "On" ]
default = "On"

[[manifest.config_options]]
id = "cmdmenu_icons_fox"
name = "Illusion Spell: Fox Icon"
description = '''
Star Fox Adventures' Kiosk build (2002) contains many leftover assets from earlier in development, for example a folder ("swapcircle") containing Dinosaur Planet inventory/HUD icons from around January 2001.

Looking through the folder's contents we can see Rare had by that stage replaced Sabre's portrait icon with a new Fox icon, designed by Nick Southam. The icon's art style closely matches the Dinosaur Planet character portraits seen in December 2000.

The Fox icon didn't end up being used in the retail Star Fox Adventures, but this config option let you see it while playing Dinosaur Planet's prototype, appearing when Sabre uses the Illusion Spell!

If you're curious about why Sabre turns into Fox when using that Spell, here's the explanation:

In the unmodified prototype, Rare replaced Sabre's gameplay and cutscene models with new Fox models, but Sabre's "high-quality textures" model and unfinished Illusion Spell models thankfully escaped being overwritten. As a funny side-effect, Fox would appear to disguise himself as Sabre whenever he used the Illusion Spell!

Dinomod Enhanced uses those surviving Sabre models to restore/recreate Sabre's gameplay and cutscene models. The Fox models were then kept and used in place of Sabre's unfinished Illusion Spell model, as a homage to the "disguise" behaviour seen in the unedited prototype.
'''
type = "Enum"
options = [ "Off", "On" ]
default = "On"

[[manifest.config_options]]
id = "cmdmenu_active_icon_overlap"
name = "Active Spell/Command: Overlap Fix"
description = '''
When a Spell or a Sidekick Command is selected in the inventory, the game's UI displays its icon in the bottom-right of screen. Both the active Spell and active Sidekick Command's icons can be shown at the same time, with the Sidekick Command stacked above the Spell.

There's a minor problem with this: the Sidekick Command icon's screen position overlaps with the position of the inventory scroll. So, if the inventory is opened while a Sidekick Command is issued, the UI elements will clash in an awkward way. This config option addresses that!

There are three options:

- Off
  The original unedited behaviour.

- On (Hide)
  The Sidekick Command icon will be hidden while the inventory is open.

- On (Move)
  The Sidekick Command icon will scoot down while the inventory is open. 
  The Spell icon will also over move if the Sidekick Icon needs space.
'''
type = "Enum"
options = [ "Off", "On (Hide)", "On (Move)" ]
default = "On (Move)"

[[manifest.config_options]]
id = "cmdmenu_active_icon_fade"
name = "Active Spell/Command: Animate Fade"
description = '''
When a Spell or a Sidekick Command is selected in the inventory, the game's UI displays its icon in the bottom-right of screen.

Unlike other elements of the UI, the active Spell/Command icons appear and disappear immediately without any fade animation.

This config option lets you add fade-in/out animation to the icons.
'''
type = "Enum"
options = [ "Off", "On" ]
default = "On"

[[manifest.config_options]]
id = "cmdmenu_sidekick_meter_hide_red"
name = "Sidekick Meter: Hide Red Food"
description = '''
In the unpatched December 2000 Prototype the sidekicks' food meter always shows hard-coded food quantities: 3 blue and 3 red.

Dinomod Enhanced connects up the sidekicks' actual food counts to the meters, letting you see Tricky's blue energy decreasing as he digs at certain spots (note that not all dig spots have an energy cost assigned).

It's not possible to increase the sidekick's red food count however, since there's no Red Mushroom inventory item. If you'd like to only see the sidekick's blue food count and exclude red food from the meter, this config option can be enabled.
'''
type = "Enum"
options = [ "Off", "On" ]
default = "On"

[[manifest.config_options]]
id = "cmdmenu_sidekick_meter_show_over_food"
name = "Sidekick Meter: While Food Selected"
description = '''
By default the sidekick food meter shows up while browsing the Sidekick inventory page, when the sidekick's food energy changes, or when the sidekick loads.

This config option allows the meter to also show up while relevant food items are highlighted in the Items inventory! This lets you check how full Tricky is while feeding him a Blue Mushroom directly from your Items (as opposed to from a sidekick food bag).
'''
type = "Enum"
options = [ "Off", "On" ]
default = "On"

[[manifest.config_options]]
id = "log_a_button"
name = "Log: Rowing Controls"
description = '''
When riding a log, whether rowing requires the A button to be tapped (vanilla) or allows A to be held to continuously row.
'''
type = "Enum"
options = [ "Tap", "Hold" ]
default = "Tap"

[[manifest.config_options]]
id = "iceblast_cost"
name = "Ice Blast Spell: Reduced Magic Cost"
description = '''
When this is enabled, using the Ice Blast Spell will drain 1 unit of magic every half-second.

In the unpatched game the Ice Blast Spell's collision detectors also drain 1 magic per half-second. However: 3 of these detector objects exist while the spell is being fired, so the depletion rate ends up tripled (possibly by mistake)!

Switching this toggle off will use the original more rapid drain.
'''
type = "Enum"
options = [ "Off", "On"]
default = "On"

[[manifest.config_options]]
id = "garunda_te_frostweeds_override"
name = "Garunda Te: Total FrostWeeds"
description = '''
Modifies the total number of FrostWeeds that need to be fed to Garunda Te before he can free himself from the ice.

12 are needed by default, but 4 is a bit more manageable!
'''
type = "Number"
min = 1
max = 20
step = 1
precision = 0
percent = false
default = 12

[[manifest.config_options]]
id = "garunda_te_frostweeds_accept_twigs"
name = "Garunda Te: Accept FrostWeed Twigs"
description = '''
Garunda Te only eats whole FrostWeeds in the original December 2000 Prototype, and won't accept any FrostWeeds Sabre carries over in their twig form. Your only option was to herd FrostWeeds towards him, which can be easier said than done!

This config switch gives you the option of directly carrying FrostWeeds over to Garunda Te.
'''
type = "Enum"
options = [ "Off", "On" ]
default = "Off"

[[manifest.config_options]]
id = "kt_mode"
name = "Klanadack"
description = '''
Options to adjust the behavior of the Klanadack boss fight.

- Vanilla: Only include bug fixes and basic polish.
- Enhanced: Small adjustments to Klanadack's behavior to improve the boss fight.
- Enhanced (Hard Mode): Everything from Enhanced but with increased difficulty.

Note: This must be set *before* entering the boss fight!
'''
type = "Enum"
options = [ "Vanilla", "Enhanced", "Enhanced (Hard Mode)" ]
default = "Enhanced"

[[manifest.config_options]]
id = "fxemit_hide_default"
name = "FXEmit: Hide Debug Flashes"
description = '''
In the unpatched game, FXEmit objects flash a default fallback particle (a small red glow) for a single frame after they load. Rare's staff may have added this behaviour intentionally to assist in configuring FXEmitters.

This setting prevents those single-frame flashes from appearing, however they can be renabled for debugging purposes.
'''
type = "Enum"
options = [ "Show", "Hide" ]
default = "Hide"

[[manifest.config_options]]
id = "magic_dust_reflect_bounce"
name = "Magic Crystals: Use Reflected Bounce"
description = '''
By default Magic Crystals' bounce behaviour treats the ground like it's perfectly flat: reversing and diminishing only the vertical component of the gem's velocity each time it bounces.

Despite this, Magic Crystals' code also contains an unused section where it calculates an accurate bounce vector reflected off the ground's angle at the point of collision! Enabling this config option lets the gems use that calculation's result, so you'll see gems bounce downhill!
'''
type = "Enum"
options = [ "Off", "On" ]
default = "Off"

[[manifest.config_options]]
id = "shmushroom_dance_chance"
name = "Mushroom Dance Chance"
description = '''
Blue/White Mushrooms have an unseen dance animation. To offer a way of seeing it, this slider lets you control the probability (in percent) of mushrooms starting to dance during their idle state!

Setting it to 0% will prevent this behaviour completely, if preferred.
'''
type = "Number"
min = 0
max = 100
step = 1
precision = 0
percent = true
default = 10

[[manifest.config_options]]
id = "dim_tent_cinders"
name = "DIM Tents: Show Cinders"
description = '''
In DarkIce Mines, one of the Bridge Cogs can be found inside burnable tents. These tents have an unreferenced model indexed just after their regular model, which seems intended to be left behind after they're burnt.

This config lets you see the model, with a few different options:

- Off
  The default behaviour: the tents disappear when burnt.

- On (Fade-Out)
  The tents leave behind their charred frame, which then gradually fades away.

- On (Persist)
  The tents leave behind their charred frame, which can still be seen when revisiting the area.
-
'''
type = "Enum"
options = [ "Off", "On (Fade-Out)", "On (Persist)" ]
default = "On (Fade-Out)"

[[manifest.config_options]]
id = "rolling_demo"
name = "Rolling Demo"
description = '''
The unpatched December 2000 Prototype skips to the Game Select screen after the Rareware logo screen, bypassing the Rolling Demo sequence.

This config option restores the Rolling Demo sequence (many thanks to nuggs!)

Alternatively, "Boot to Game Select" can be used as a convenience when modding the game.
'''
type = "Enum"
options = [ "Off", "On", "Boot to Game Select" ]
default = "On"
